version: '3.7'
services:
  portfolio-db:
    container_name: dev-postgres
    ports:
      - "5432:5432"
    image: postgres:15
    networks:
      - portfolio-network
    environment:
      - POSTGRES_DATABASE=portfoliodb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_ROOT_PASSWORD=secret
    volumes:
      - dbvol:/var/lib/postgresql
    restart: always


  portfolio-app:
    build:
      context: .
    container_name: portfolio-app
    image: portfolio:latest
    ports:
      - "8080:8080"
    networks:
      - portfolio-network
    depends_on:
      - portfolio-db
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_DATABASE=portfoliodb
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432

networks:
  portfolio-network:
    name: portfolio-network

volumes:
  dbvol: