CREATE TABLE users
(
    user_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name      varchar(100) UNIQUE NOT NULL,
    user_portfolio int                 not null REFERENCES portfolio (portfolio_id) ON DELETE CASCADE
);

create table quotes
(
    symbol varchar(15)  not null primary key,
    price  varchar(100) not null
);

CREATE TABLE coins
(
    coin_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coin_symbol varchar(15)  not null,
    coin_price  varchar(100) not null,
    symbol      varchar(15)  not null REFERENCES quotes (symbol) ON DELETE CASCADE
);

create table portfolio
(
    portfolio_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_name varchar(100) not null,
    coin_id        INT          NOT NULL REFERENCES coins (coin_id) ON DELETE CASCADE
);

alter table quotes
    owner to admin;

alter table portfolio
    owner to admin;

alter table coins
    owner to admin;
