create table quotes
(
    symbol varchar(15)  not null,
    price  varchar(100) not null,
    PRIMARY KEY (symbol)
);

CREATE TABLE users
(
    user_id       INT                 NOT NULL,
    user_name     varchar(100) UNIQUE NOT NULL,
    user_password varchar(100) UNIQUE NOT NULL,
    PRIMARY KEY (user_id)
);

create table portfolio
(
    portfolio_id   INT          NOT NULL,
    portfolio_name varchar(100) not null,
    PRIMARY KEY (portfolio_id),
    user_id        int          not null REFERENCES users (user_id) ON DELETE CASCADE
);

alter table users
    add column portfolio_id INT NOT NULL
        REFERENCES portfolio (portfolio_id)
            ON DELETE CASCADE;

CREATE TABLE coins
(
    coin_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    coin_symbol    varchar(15) UNIQUE not null,
    coin_buy_price varchar(100)       not null,
    portfolio_id   INT                NOT NULL REFERENCES portfolio (portfolio_id) ON DELETE CASCADE
);

alter table portfolio
    add column coins_id int not null
        REFERENCES coins (coin_id)
            ON DELETE CASCADE;
